OTP_LENGTH = 6                  
OTP_EXPIRY_MINUTES = 10         


EMAIL_SUBJECT_OTP = "Your Helix Flow OTP Code"
EMAIL_SUBJECT_WELCOME = "Welcome to Helix Flow!"


TASK_STATUS_PENDING = "pending"
TASK_STATUS_IN_PROGRESS = "in_progress"
TASK_STATUS_COMPLETED = "completed"
TASK_STATUS_CHOICES = [
    TASK_STATUS_PENDING,
    TASK_STATUS_IN_PROGRESS,
    TASK_STATUS_COMPLETED,
]


TASK_PRIORITY_LOW = "low"
TASK_PRIORITY_MEDIUM = "medium"
TASK_PRIORITY_HIGH = "high"
TASK_PRIORITY_CHOICES = [
    TASK_PRIORITY_LOW,
    TASK_PRIORITY_MEDIUM,
    TASK_PRIORITY_HIGH,
] 